/**
 * Estilos para ProfileScreen y subcomponentes
 */
import { StyleSheet } from 'react-native';
import {
  COLORS,
  BACKGROUND_OPACITY,
  HEADER_PADDING_HORIZONTAL,
  HEADER_PADDING_VERTICAL,
  HEADER_BORDER_WIDTH,
  HEADER_BUTTON_SIZE,
  HEADER_BUTTON_BORDER_RADIUS,
  PROFILE_SECTION_PADDING,
  USER_NAME_MARGIN_BOTTOM,
  USER_EMAIL_MARGIN_BOTTOM,
  STATS_CONTAINER_PADDING,
  SECTION_TITLE_MARGIN_BOTTOM,
  STATS_GRID_PADDING_VERTICAL,
  STAT_ITEM_WIDTH,
  STAT_ITEM_BORDER_RADIUS,
  STAT_ITEM_PADDING,
  STAT_ITEM_MARGIN_RIGHT,
  STAT_ITEM_BORDER_WIDTH,
  STAT_VALUE_MARGIN_VERTICAL,
  STAT_SUB_LABEL_MARGIN_TOP,
  OPTIONS_CONTAINER_PADDING,
  OPTION_BUTTON_BORDER_RADIUS,
  OPTION_BUTTON_PADDING,
  OPTION_BUTTON_MARGIN_BOTTOM,
  OPTION_BUTTON_BORDER_WIDTH,
  OPTION_TEXT_MARGIN_LEFT,
  LOGOUT_BUTTON_BORDER_RADIUS,
  LOGOUT_BUTTON_PADDING,
  LOGOUT_BUTTON_MARGIN,
  LOGOUT_BUTTON_BORDER_WIDTH,
  LOGOUT_TEXT_MARGIN_LEFT,
  LOADING_TEXT_MARGIN_TOP,
} from './profileScreenConstants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  background: {
    flex: 1,
  },
  imageStyle: {
    opacity: BACKGROUND_OPACITY,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.BACKGROUND,
  },
  loadingText: {
    color: COLORS.ACCENT,
    fontSize: 18,
    marginTop: LOADING_TEXT_MARGIN_TOP,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: HEADER_PADDING_HORIZONTAL,
    paddingVertical: HEADER_PADDING_VERTICAL,
    backgroundColor: COLORS.HEADER_BACKGROUND,
    borderBottomWidth: HEADER_BORDER_WIDTH,
    borderBottomColor: COLORS.HEADER_BORDER,
  },
  headerButton: {
    width: HEADER_BUTTON_SIZE,
    height: HEADER_BUTTON_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: HEADER_BUTTON_BORDER_RADIUS,
    backgroundColor: COLORS.HEADER_BUTTON_BACKGROUND,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.WHITE,
    textAlign: 'center',
  },
  profileSection: {
    alignItems: 'center',
    padding: PROFILE_SECTION_PADDING,
  },
  userName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.WHITE,
    marginBottom: USER_NAME_MARGIN_BOTTOM,
  },
  userEmail: {
    fontSize: 16,
    color: COLORS.ACCENT,
    marginBottom: USER_EMAIL_MARGIN_BOTTOM,
  },
  subscriptionContainer: {
    padding: STATS_CONTAINER_PADDING,
  },
  statsContainer: {
    padding: STATS_CONTAINER_PADDING,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.WHITE,
    marginBottom: SECTION_TITLE_MARGIN_BOTTOM,
  },
  statsGrid: {
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingVertical: STATS_GRID_PADDING_VERTICAL,
  },
  statItem: {
    width: STAT_ITEM_WIDTH,
    backgroundColor: COLORS.CARD_BACKGROUND,
    borderRadius: STAT_ITEM_BORDER_RADIUS,
    padding: STAT_ITEM_PADDING,
    alignItems: 'center',
    marginRight: STAT_ITEM_MARGIN_RIGHT,
    borderWidth: STAT_ITEM_BORDER_WIDTH,
    borderColor: COLORS.CARD_BORDER,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.WHITE,
    marginVertical: STAT_VALUE_MARGIN_VERTICAL,
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.ACCENT,
    textAlign: 'center',
  },
  statSubLabel: {
    fontSize: 10,
    color: COLORS.ACCENT,
    textAlign: 'center',
    marginTop: STAT_SUB_LABEL_MARGIN_TOP,
  },
  optionsContainer: {
    padding: OPTIONS_CONTAINER_PADDING,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.CARD_BACKGROUND,
    borderRadius: OPTION_BUTTON_BORDER_RADIUS,
    padding: OPTION_BUTTON_PADDING,
    marginBottom: OPTION_BUTTON_MARGIN_BOTTOM,
    borderWidth: OPTION_BUTTON_BORDER_WIDTH,
    borderColor: COLORS.CARD_BORDER,
  },
  optionText: {
    flex: 1,
    marginLeft: OPTION_TEXT_MARGIN_LEFT,
    fontSize: 16,
    color: COLORS.WHITE,
  },
  optionContent: {
    flex: 1,
    marginLeft: OPTION_TEXT_MARGIN_LEFT,
  },
  optionSubtext: {
    fontSize: 12,
    color: COLORS.ACCENT,
    marginTop: 2,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.LOGOUT_BUTTON_BACKGROUND,
    borderRadius: LOGOUT_BUTTON_BORDER_RADIUS,
    padding: LOGOUT_BUTTON_PADDING,
    margin: LOGOUT_BUTTON_MARGIN,
    borderWidth: LOGOUT_BUTTON_BORDER_WIDTH,
    borderColor: COLORS.LOGOUT_BUTTON_BORDER,
  },
  logoutText: {
    marginLeft: LOGOUT_TEXT_MARGIN_LEFT,
    fontSize: 16,
    color: COLORS.ERROR,
    fontWeight: '500',
  },
  separator: {
    height: 1,
    backgroundColor: COLORS.CARD_BORDER,
    marginVertical: 20,
    marginHorizontal: OPTIONS_CONTAINER_PADDING,
  },
  emergencyContactsSection: {
    marginBottom: 16,
  },
  contactsList: {
    marginTop: 12,
  },
  contactItem: {
    backgroundColor: COLORS.CARD_BACKGROUND,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.CARD_BORDER,
  },
  contactMainContent: {
    flex: 1,
  },
  contactHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  contactHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  contactTitleContainer: {
    flex: 1,
  },
  contactName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.WHITE,
    marginBottom: 2,
  },
  contactRelationship: {
    fontSize: 12,
    color: COLORS.ACCENT,
    fontStyle: 'italic',
  },
  contactDetails: {
    marginLeft: 0,
    gap: 6,
  },
  contactDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  contactDetailText: {
    fontSize: 13,
    color: COLORS.ACCENT,
    flex: 1,
  },
  contactActions: {
    flexDirection: 'row',
    gap: 6,
  },
  contactActionButton: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: 'rgba(26, 221, 219, 0.1)',
    minWidth: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactActionButtonDelete: {
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
  },
  emptyText: {
    fontSize: 14,
    color: COLORS.ACCENT,
    textAlign: 'center',
    padding: 16,
    fontStyle: 'italic',
  },
});
