import { StyleSheet } from 'react-native';
import { colors } from '../../styles/globalStyles';
import { TYPOGRAPHY } from '../../constants/ui';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 10,
    gap: 12,
  },
  topBarDivider: {
    height: 1,
    marginHorizontal: 20,
    backgroundColor: colors.border,
    opacity: 0.85,
  },
  topBarTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  subtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  statsButtonIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: `${colors.primary}18`,
    borderWidth: 1,
    borderColor: colors.border,
  },
  emotionToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 10,
    paddingVertical: 6,
    paddingLeft: 6,
    paddingRight: 10,
    borderRadius: 12,
    backgroundColor: colors.cardBackground,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 6,
  },
  emotionToggleMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 8,
    minWidth: 0,
  },
  emotionToggleLabel: {
    flex: 1,
    fontSize: TYPOGRAPHY.CAPTION,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  emotionToggleValue: {
    fontSize: TYPOGRAPHY.CAPTION,
    color: colors.text,
    fontWeight: '600',
    maxWidth: '38%',
  },
  clearFilterLink: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  emotionFilter: {
    maxHeight: 64,
    marginBottom: 12,
  },
  emotionFilterContent: {
    paddingHorizontal: 20,
    paddingBottom: 4,
    gap: 8,
  },
  emotionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: colors.cardBackground,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 6,
  },
  emotionButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  emotionButtonText: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: '500',
  },
  emotionButtonTextActive: {
    color: colors.white,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 120,
  },
  listIntro: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 12,
    borderRadius: 12,
    backgroundColor: `${colors.primary}12`,
    borderWidth: 1,
    borderColor: colors.border,
  },
  listIntroText: {
    flex: 1,
    fontSize: TYPOGRAPHY.CAPTION,
    color: colors.textSecondary,
    lineHeight: 19,
  },
  categorySection: {
    marginBottom: 10,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingVertical: 12,
    paddingRight: 4,
    paddingLeft: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    borderLeftWidth: 4,
  },
  categoryHeaderInner: {
    flex: 1,
    minWidth: 0,
  },
  categoryHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  categoryHeaderMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  categoryHint: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
    marginTop: 8,
    paddingRight: 28,
  },
  categoryTitleShort: {
    fontSize: TYPOGRAPHY.BODY,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: 0.2,
  },
  categoryCountBadge: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
    backgroundColor: `${colors.primary}22`,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    overflow: 'hidden',
  },
  categoryCards: {
    paddingTop: 12,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    marginTop: 15,
    fontSize: TYPOGRAPHY.BODY,
    color: colors.textSecondary,
  },
  errorText: {
    marginTop: 15,
    fontSize: TYPOGRAPHY.BODY,
    color: colors.error,
    textAlign: 'center',
  },
  emptyText: {
    marginTop: 15,
    fontSize: TYPOGRAPHY.BODY,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 20,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: colors.primary,
  },
  retryButtonText: {
    color: colors.white,
    fontSize: TYPOGRAPHY.BODY,
    fontWeight: '600',
  },
});
