/**
 * Mensajes de API de autenticación (es/en).
 */
import { normalizeApiLanguage } from './apiLanguage.js';

const COPY = {
  es: {
    invalidData: 'Datos inválidos',
    validationError: 'Error de validación',
    rateLimitLogin:
      'Demasiados intentos de inicio de sesión. Por favor, intente más tarde.',
    rateLimitRegister:
      'Demasiados intentos de registro. Por favor, intente más tarde.',
    rateLimitPasswordReset:
      'Demasiados intentos de recuperación de contraseña. Por favor, intente más tarde.',
    rateLimitChangePassword:
      'Demasiados intentos de cambio de contraseña. Por favor, intente más tarde.',
    emailOrUsernameInUse: 'El email o nombre de usuario ya está en uso',
    registerSuccess:
      'Usuario registrado exitosamente. Por favor verifica tu email.',
    registerError: 'Error al registrar usuario',
    emailNotFound: 'No existe una cuenta con este correo electrónico',
    emailAlreadyVerified: 'El email ya está verificado',
    invalidOrExpiredCode: 'Código inválido o expirado',
    resetCodeInvalid: 'El código no es correcto. Revísalo e inténtalo de nuevo.',
    resetCodeExpired: 'El código expiró. Solicita uno nuevo.',
    verifyEmailSuccess: 'Email verificado exitosamente',
    verifyEmailError: 'Error al verificar el email',
    resendCodeSuccess: 'Código de verificación reenviado exitosamente',
    resendCodeSendError: 'Error al enviar el código de verificación',
    requestProcessError: 'Error al procesar la solicitud',
    invalidCredentials: 'Credenciales incorrectas',
    accountDeactivated: 'Tu cuenta ha sido desactivada. Contacta al soporte.',
    verifyEmailBeforeLogin:
      'Por favor verifica tu email antes de iniciar sesión. Revisa tu correo para el código de verificación.',
    loginError: 'Error al iniciar sesión',
    refreshTokenRequired: 'Refresh token es requerido',
    invalidToken: 'Token inválido',
    userNotFoundInactive: 'Usuario no encontrado o inactivo',
    tokenInvalidOrExpired: 'Token inválido o expirado',
    activeRecoveryCodeExists:
      'Ya existe un código de recuperación activo. Por favor, espere a que expire.',
    verificationCodeSent: 'Se ha enviado un código de verificación a tu correo',
    codeVerifiedSuccess: 'Código verificado correctamente',
    codeVerifyError: 'Error al verificar el código',
    passwordResetSuccess: 'Contraseña restablecida correctamente',
    passwordResetError: 'Error al restablecer la contraseña',
    userNotFound: 'Usuario no encontrado',
    wrongCurrentPassword: 'La contraseña actual es incorrecta',
    passwordSameAsCurrent: 'La nueva contraseña debe ser diferente a la actual',
    passwordUpdatedSuccess: 'Contraseña actualizada correctamente',
    changePasswordError: 'Error al cambiar la contraseña',
    logoutSuccess: 'Sesión cerrada correctamente',
    logoutError: 'Error al cerrar sesión',
    joiEmailInvalid: 'Por favor ingresa un email válido',
    joiEmailRequired: 'El email es requerido',
    joiPasswordMin8: 'La contraseña debe tener al menos 8 caracteres',
    joiPasswordRequired: 'La contraseña es requerida',
    joiUsernameMin: 'El nombre de usuario debe tener al menos 3 caracteres',
    joiUsernameMax: 'El nombre de usuario debe tener máximo 20 caracteres',
    joiUsernamePattern:
      'El nombre de usuario solo puede contener letras minúsculas, números y guiones bajos',
    joiUsernameRequired: 'El nombre de usuario es requerido',
    joiNameMin: 'El nombre debe tener al menos 2 caracteres',
    joiNameMax: 'El nombre debe tener máximo 50 caracteres',
    joiTermsRequired: 'Debes aceptar los términos y condiciones',
    joiPrivacyRequired: 'Debes aceptar la política de privacidad',
    joiCodeLength: 'El código debe tener 6 dígitos',
    joiCodePattern: 'El código debe contener solo números',
    joiCodeRequired: 'El código es requerido',
    joiNewPasswordMin8: 'La nueva contraseña debe tener al menos 8 caracteres',
    joiNewPasswordRequired: 'La nueva contraseña es requerida',
    joiCurrentPasswordRequired: 'La contraseña actual es obligatoria',
    joiCurrentPasswordEmpty: 'La contraseña actual es obligatoria',
    joiNewPasswordMin6: 'La nueva contraseña debe tener al menos 6 caracteres',
    joiNewPasswordEmpty: 'La nueva contraseña es obligatoria',
  },
  en: {
    invalidData: 'Invalid data',
    validationError: 'Validation error',
    rateLimitLogin: 'Too many sign-in attempts. Please try again later.',
    rateLimitRegister: 'Too many registration attempts. Please try again later.',
    rateLimitPasswordReset:
      'Too many password recovery attempts. Please try again later.',
    rateLimitChangePassword:
      'Too many password change attempts. Please try again later.',
    emailOrUsernameInUse: 'Email or username is already in use',
    registerSuccess: 'Account created successfully. Please verify your email.',
    registerError: 'Could not register user',
    emailNotFound: 'No account exists with this email address',
    emailAlreadyVerified: 'Email is already verified',
    invalidOrExpiredCode: 'Invalid or expired code',
    resetCodeInvalid: 'The code is incorrect. Check it and try again.',
    resetCodeExpired: 'The code has expired. Request a new one.',
    verifyEmailSuccess: 'Email verified successfully',
    verifyEmailError: 'Could not verify email',
    resendCodeSuccess: 'Verification code resent successfully',
    resendCodeSendError: 'Could not send verification code',
    requestProcessError: 'Could not process request',
    invalidCredentials: 'Incorrect credentials',
    accountDeactivated: 'Your account has been deactivated. Contact support.',
    verifyEmailBeforeLogin:
      'Please verify your email before signing in. Check your inbox for the verification code.',
    loginError: 'Could not sign in',
    refreshTokenRequired: 'Refresh token is required',
    invalidToken: 'Invalid token',
    userNotFoundInactive: 'User not found or inactive',
    tokenInvalidOrExpired: 'Invalid or expired token',
    activeRecoveryCodeExists:
      'An active recovery code already exists. Please wait for it to expire.',
    verificationCodeSent: 'A verification code has been sent to your email',
    codeVerifiedSuccess: 'Code verified successfully',
    codeVerifyError: 'Could not verify code',
    passwordResetSuccess: 'Password reset successfully',
    passwordResetError: 'Could not reset password',
    userNotFound: 'User not found',
    wrongCurrentPassword: 'Current password is incorrect',
    passwordSameAsCurrent: 'New password must be different from the current one',
    passwordUpdatedSuccess: 'Password updated successfully',
    changePasswordError: 'Could not change password',
    logoutSuccess: 'Signed out successfully',
    logoutError: 'Could not sign out',
    joiEmailInvalid: 'Please enter a valid email address',
    joiEmailRequired: 'Email is required',
    joiPasswordMin8: 'Password must be at least 8 characters',
    joiPasswordRequired: 'Password is required',
    joiUsernameMin: 'Username must be at least 3 characters',
    joiUsernameMax: 'Username must be at most 20 characters',
    joiUsernamePattern:
      'Username may only contain lowercase letters, numbers, and underscores',
    joiUsernameRequired: 'Username is required',
    joiNameMin: 'Name must be at least 2 characters',
    joiNameMax: 'Name must be at most 50 characters',
    joiTermsRequired: 'You must accept the terms and conditions',
    joiPrivacyRequired: 'You must accept the privacy policy',
    joiCodeLength: 'Code must be 6 digits',
    joiCodePattern: 'Code must contain numbers only',
    joiCodeRequired: 'Code is required',
    joiNewPasswordMin8: 'New password must be at least 8 characters',
    joiNewPasswordRequired: 'New password is required',
    joiCurrentPasswordRequired: 'Current password is required',
    joiCurrentPasswordEmpty: 'Current password is required',
    joiNewPasswordMin6: 'New password must be at least 6 characters',
    joiNewPasswordEmpty: 'New password is required',
  },
};

export function authApiCopy(language) {
  return COPY[normalizeApiLanguage(language)];
}
