/**
 * Mensajes de API de pensamientos automáticos (#89).
 */
import { normalizeApiLanguage } from './apiLanguage.js';

const COPY = {
  es: {
    rateLimitCreate:
      'Demasiados registros creados. Por favor, intente más tarde.',
    rateLimitDelete:
      'Demasiadas eliminaciones. Por favor, intente más tarde.',
    listError: 'Error al obtener los registros de pensamientos automáticos',
    notFound: 'Registro no encontrado',
    getError: 'Error al obtener el registro',
    createdSuccess: 'Pensamiento registrado',
    createError: 'Error al crear el registro',
    deletedSuccess: 'Registro eliminado',
    deleteError: 'Error al eliminar el registro',
    exportError: 'Error al exportar los registros',
    exportHeader: 'Pensamientos automáticos — resumen para revisión',
    exportSituation: 'Situación',
    exportThought: 'Pensamiento automático',
    exportEmotion: 'Emoción',
    exportIntensity: 'Intensidad',
    exportDistortion: 'Patrón',
    exportBalanced: 'Pensamiento alternativo',
    exportNotes: 'Notas',
    exportDate: 'Fecha',
    joiSituationEmpty: 'La situación no puede estar vacía',
    joiSituationMax: 'La situación no puede exceder 500 caracteres',
    joiSituationRequired: 'La situación es requerida',
    joiThoughtEmpty: 'El pensamiento no puede estar vacío',
    joiThoughtMax: 'El pensamiento no puede exceder 500 caracteres',
    joiThoughtRequired: 'El pensamiento automático es requerido',
    joiEmotionMax: 'La emoción no puede exceder 100 caracteres',
    joiIntensityMin: 'La intensidad mínima es 1',
    joiIntensityMax: 'La intensidad máxima es 10',
    joiDistortionTypeInvalid: 'Tipo de distorsión inválido',
    joiDistortionNameMax: 'El nombre de distorsión no puede exceder 200 caracteres',
    joiBalancedMax: 'El pensamiento alternativo no puede exceder 500 caracteres',
    joiNotesMax: 'Las notas no pueden exceder 500 caracteres',
  },
  en: {
    rateLimitCreate: 'Too many records created. Please try again later.',
    rateLimitDelete: 'Too many deletions. Please try again later.',
    listError: 'Could not load automatic thought records',
    notFound: 'Record not found',
    getError: 'Could not load record',
    createdSuccess: 'Thought logged',
    createError: 'Could not create record',
    deletedSuccess: 'Record deleted',
    deleteError: 'Could not delete record',
    exportError: 'Could not export records',
    exportHeader: 'Automatic thoughts — summary for review',
    exportSituation: 'Situation',
    exportThought: 'Automatic thought',
    exportEmotion: 'Emotion',
    exportIntensity: 'Intensity',
    exportDistortion: 'Pattern',
    exportBalanced: 'Alternative thought',
    exportNotes: 'Notes',
    exportDate: 'Date',
    joiSituationEmpty: 'Situation cannot be empty',
    joiSituationMax: 'Situation cannot exceed 500 characters',
    joiSituationRequired: 'Situation is required',
    joiThoughtEmpty: 'Thought cannot be empty',
    joiThoughtMax: 'Thought cannot exceed 500 characters',
    joiThoughtRequired: 'Automatic thought is required',
    joiEmotionMax: 'Emotion cannot exceed 100 characters',
    joiIntensityMin: 'Minimum intensity is 1',
    joiIntensityMax: 'Maximum intensity is 10',
    joiDistortionTypeInvalid: 'Invalid distortion type',
    joiDistortionNameMax: 'Distortion name cannot exceed 200 characters',
    joiBalancedMax: 'Alternative thought cannot exceed 500 characters',
    joiNotesMax: 'Notes cannot exceed 500 characters',
  },
};

export function automaticThoughtApiCopy(language) {
  return COPY[normalizeApiLanguage(language)];
}
