/**
 * Mensajes de API de activación conductual (#88).
 */
import { normalizeApiLanguage } from './apiLanguage.js';

const COPY = {
  es: {
    rateLimitCreate:
      'Demasiados registros creados. Por favor, intente más tarde.',
    rateLimitDelete:
      'Demasiadas eliminaciones. Por favor, intente más tarde.',
    listError: 'Error al obtener los registros de activación conductual',
    notFound: 'Registro no encontrado',
    getError: 'Error al obtener el registro',
    createdSuccess: 'Actividad registrada',
    createError: 'Error al crear el registro',
    deletedSuccess: 'Registro eliminado',
    deleteError: 'Error al eliminar el registro',
    exportError: 'Error al exportar los registros',
    exportHeader: 'Activación conductual — resumen para revisión',
    exportActivity: 'Actividad',
    exportType: 'Tipo',
    exportTypePleasant: 'Placentera',
    exportTypeRoutine: 'Rutina / obligatoria',
    exportMoodBefore: 'Ánimo antes',
    exportMoodAfter: 'Ánimo después',
    exportNotes: 'Notas',
    exportDate: 'Fecha',
    joiActivityEmpty: 'La actividad no puede estar vacía',
    joiActivityMax: 'La actividad no puede exceder 500 caracteres',
    joiActivityRequired: 'La actividad es requerida',
    joiTypeInvalid: 'Tipo de actividad inválido',
    joiMoodBeforeRequired: 'El ánimo antes es requerido',
    joiMoodAfterRequired: 'El ánimo después es requerido',
    joiMoodMin: 'El ánimo mínimo es 1',
    joiMoodMax: 'El ánimo máximo es 10',
    joiNotesMax: 'Las notas no pueden exceder 500 caracteres',
    weekPlanError: 'Error al obtener el plan semanal',
    weekPlanSaveError: 'Error al guardar el plan semanal',
    weekPlanSaved: 'Plan semanal actualizado',
    joiWeekStartInvalid: 'Fecha de semana inválida (use YYYY-MM-DD)',
    joiSlotIdRequired: 'Cada actividad debe tener un identificador',
    joiDayOffsetRequired: 'Día de la semana requerido',
    joiSlotStatusInvalid: 'Estado de actividad inválido',
    joiCompletedLogInvalid: 'Registro completado inválido',
    joiSlotsMin: 'El plan debe incluir al menos una actividad',
    joiSlotsMax: 'El plan admite como máximo 7 actividades',
    joiSlotsRequired: 'Las actividades del plan son requeridas',
    joiProductKindInvalid: 'Tipo de vínculo inválido (task, habit o auto)',
    linkProductSuccess: 'Actividad vinculada a tu espacio de producto',
    linkProductError: 'No se pudo vincular la actividad',
    linkProductPlanNotFound: 'Plan semanal no encontrado',
    linkProductSlotNotFound: 'Actividad del plan no encontrada',
    linkProductConflict: 'Esta actividad ya está vinculada a otro tipo (tarea u hábito)',
    linkProductValidationError: 'No se pudo crear la tarea o el hábito (revisa la fecha o el título)',
    syncFromLogSuccess: 'Actividad sincronizada con tu plan',
    syncFromLogError: 'No se pudo sincronizar el plan con Tareas/Hábitos',
  },
  en: {
    rateLimitCreate: 'Too many records created. Please try again later.',
    rateLimitDelete: 'Too many deletions. Please try again later.',
    listError: 'Could not load behavioral activation records',
    notFound: 'Record not found',
    getError: 'Could not load record',
    createdSuccess: 'Activity logged',
    createError: 'Could not create record',
    deletedSuccess: 'Record deleted',
    deleteError: 'Could not delete record',
    exportError: 'Could not export records',
    exportHeader: 'Behavioral activation — summary for review',
    exportActivity: 'Activity',
    exportType: 'Type',
    exportTypePleasant: 'Pleasant',
    exportTypeRoutine: 'Routine / necessary',
    exportMoodBefore: 'Mood before',
    exportMoodAfter: 'Mood after',
    exportNotes: 'Notes',
    exportDate: 'Date',
    joiActivityEmpty: 'Activity cannot be empty',
    joiActivityMax: 'Activity cannot exceed 500 characters',
    joiActivityRequired: 'Activity is required',
    joiTypeInvalid: 'Invalid activity type',
    joiMoodBeforeRequired: 'Mood before is required',
    joiMoodAfterRequired: 'Mood after is required',
    joiMoodMin: 'Minimum mood is 1',
    joiMoodMax: 'Maximum mood is 10',
    joiNotesMax: 'Notes cannot exceed 500 characters',
    weekPlanError: 'Could not load weekly plan',
    weekPlanSaveError: 'Could not save weekly plan',
    weekPlanSaved: 'Weekly plan updated',
    joiWeekStartInvalid: 'Invalid week date (use YYYY-MM-DD)',
    joiSlotIdRequired: 'Each activity must have an identifier',
    joiDayOffsetRequired: 'Day of week is required',
    joiSlotStatusInvalid: 'Invalid activity status',
    joiCompletedLogInvalid: 'Invalid completed log reference',
    joiSlotsMin: 'The plan must include at least one activity',
    joiSlotsMax: 'The plan allows at most 7 activities',
    joiSlotsRequired: 'Plan activities are required',
    joiProductKindInvalid: 'Invalid link type (task, habit, or auto)',
    linkProductSuccess: 'Activity linked to your tasks or habits',
    linkProductError: 'Could not link activity',
    linkProductPlanNotFound: 'Weekly plan not found',
    linkProductSlotNotFound: 'Plan activity not found',
    linkProductConflict: 'This activity is already linked to the other type (task or habit)',
    linkProductValidationError: 'Could not create the task or habit (check date or title)',
    syncFromLogSuccess: 'Activity synced with your plan',
    syncFromLogError: 'Could not sync plan with Tasks/Habits',
  },
};

export function behavioralActivationApiCopy(language) {
  return COPY[normalizeApiLanguage(language)];
}
