/**
 * Mensajes de API de jerarquía de exposición (#87).
 */
import { normalizeApiLanguage } from './apiLanguage.js';

const COPY = {
  es: {
    rateLimitCreate:
      'Demasiados planes creados. Por favor, intente más tarde.',
    rateLimitAttempt:
      'Demasiados intentos registrados. Por favor, intente más tarde.',
    rateLimitDelete:
      'Demasiadas eliminaciones. Por favor, intente más tarde.',
    listError: 'Error al obtener los planes de exposición',
    notFound: 'Plan no encontrado',
    getError: 'Error al obtener el plan',
    createdSuccess: 'Jerarquía de exposición guardada',
    createError: 'Error al crear el plan',
    attemptSuccess: 'Intento registrado',
    attemptError: 'Error al registrar el intento',
    stepCompleteSuccess: 'Paso completado',
    stepCompleteError: 'Error al completar el paso',
    deletedSuccess: 'Plan eliminado',
    deleteError: 'Error al eliminar el plan',
    exportError: 'Error al exportar los planes',
    exportHeader: 'Jerarquía de exposición — resumen para revisión',
    exportDisclaimer:
      'Herramienta de apoyo; no sustituye terapia de exposición presencial.',
    exportGoal: 'Objetivo',
    exportStep: 'Paso',
    exportStatus: 'Estado',
    exportAttempts: 'Intentos',
    exportPeakSuds: 'SUDS pico',
    exportEndSuds: 'SUDS final',
    exportNotes: 'Notas',
    exportDate: 'Fecha',
    statusPending: 'pendiente',
    statusInProgress: 'en curso',
    statusCompleted: 'completado',
    stepLocked: 'Completa el paso anterior antes de avanzar',
    stepIndexInvalid: 'Índice de paso inválido',
    stepAlreadyCompleted: 'Este paso ya está completado',
    stepNeedsAttempt: 'Registra al menos un intento antes de completar el paso',
    joiTitleEmpty: 'El objetivo no puede estar vacío',
    joiTitleMax: 'El objetivo no puede exceder 200 caracteres',
    joiTitleRequired: 'El objetivo es requerido',
    joiStepsMin: 'Agrega al menos 2 pasos',
    joiStepsMax: 'Máximo 15 pasos por jerarquía',
    joiStepEmpty: 'La descripción del paso no puede estar vacía',
    joiStepMax: 'La descripción no puede exceder 500 caracteres',
    joiPeakSudsRequired: 'El SUDS pico es requerido',
    joiEndSudsRequired: 'El SUDS final es requerido',
    joiSudsMin: 'El SUDS mínimo es 0',
    joiSudsMax: 'El SUDS máximo es 100',
    joiNotesMax: 'Las notas no pueden exceder 500 caracteres',
  },
  en: {
    rateLimitCreate: 'Too many exposure plans created. Please try again later.',
    rateLimitAttempt: 'Too many attempts logged. Please try again later.',
    rateLimitDelete: 'Too many deletions. Please try again later.',
    listError: 'Could not load exposure plans',
    notFound: 'Plan not found',
    getError: 'Could not load plan',
    createdSuccess: 'Exposure hierarchy saved',
    createError: 'Could not create plan',
    attemptSuccess: 'Attempt logged',
    attemptError: 'Could not log attempt',
    stepCompleteSuccess: 'Step completed',
    stepCompleteError: 'Could not complete step',
    deletedSuccess: 'Plan deleted',
    deleteError: 'Could not delete plan',
    exportError: 'Could not export plans',
    exportHeader: 'Exposure hierarchy — summary for review',
    exportDisclaimer:
      'Support tool only; does not replace in-person exposure therapy.',
    exportGoal: 'Goal',
    exportStep: 'Step',
    exportStatus: 'Status',
    exportAttempts: 'Attempts',
    exportPeakSuds: 'Peak SUDS',
    exportEndSuds: 'End SUDS',
    exportNotes: 'Notes',
    exportDate: 'Date',
    statusPending: 'pending',
    statusInProgress: 'in progress',
    statusCompleted: 'completed',
    stepLocked: 'Complete the previous step before advancing',
    stepIndexInvalid: 'Invalid step index',
    stepAlreadyCompleted: 'This step is already completed',
    stepNeedsAttempt: 'Log at least one attempt before completing the step',
    joiTitleEmpty: 'Goal cannot be empty',
    joiTitleMax: 'Goal cannot exceed 200 characters',
    joiTitleRequired: 'Goal is required',
    joiStepsMin: 'Add at least 2 steps',
    joiStepsMax: 'Maximum 15 steps per hierarchy',
    joiStepEmpty: 'Step description cannot be empty',
    joiStepMax: 'Description cannot exceed 500 characters',
    joiPeakSudsRequired: 'Peak SUDS is required',
    joiEndSudsRequired: 'End SUDS is required',
    joiSudsMin: 'Minimum SUDS is 0',
    joiSudsMax: 'Maximum SUDS is 100',
    joiNotesMax: 'Notes cannot exceed 500 characters',
  },
};

export function exposurePlanApiCopy(language) {
  return COPY[normalizeApiLanguage(language)];
}
