/**
 * Etiquetas en inglés del catálogo de intervenciones (#127 / i18n).
 * Mantener 1:1 con claves de INTERVENTION_CATALOG.
 */
export const INTERVENTION_LABELS_EN = {
  breathing_exercise: 'Breathing Exercise',
  grounding_technique: 'Grounding Technique',
  mindfulness_reminder: 'Mindfulness Reminder',
  self_care: 'Self-Care',
  self_compassion_exercise: 'Self-Compassion Exercise',
  support_contact: 'Contact Support',
  gratitude_journal: 'Gratitude Journal',
  abc_record: 'ABC Self-Monitoring',
  exposure_hierarchy: 'Exposure Hierarchy + SUDS',
  behavioral_activation: 'Behavioral Activation',
  automatic_thought_record: 'Automatic thought',
  timeout_technique: 'Time-Out Technique',
  communication_tool: 'Communication Tool',
  boundary_setting: 'Set Boundaries',
  task_break: 'Take a Break',
  grief_support: 'Grief Support',
  memory_exercise: 'Memory Exercise',
  connection_exercise: 'Connection Exercise',
  social_activity: 'Social Activity',
  activity_suggestion: 'Activity Suggestion',
  performance_anxiety_tool: 'Performance Anxiety (brief guide)',
  present_moment_exercise: 'Back to the Present (brief exercise)',
  social_anxiety_tool: 'Social Anxiety (brief guide)',
  exposure_guide: 'Gradual Exposure (brief guide)',
  reframing_tool: 'Reframing (shift perspective)',
  task_organization: 'Organize Tasks (quick steps)',
  time_management: 'Time Management (quick tip)',
  anger_management: 'Manage Anger (brief guide)',
  physical_activity: 'Gentle Movement',
  forgiveness_work: 'Forgiveness (brief exercise)',
  values_exploration: 'Explore Values (brief guide)',
  apology_guide: 'Apologize (brief guide)',
  grief_roadmap: 'Grief roadmap (brief guide)',
  relapse_prevention: 'Relapse prevention (brief plan)',
  dbt_stop_skill: 'STOP skill (regulation)',
  act_values_check: 'Values check-in (ACT-lite)',
  sleep_diary_lite: 'Brief sleep diary',
  mindfulness_sequence: 'Mindfulness sequence (MBSR-lite)',
  assertive_i_messages: 'I-messages (assertiveness)',
  problem_solving_psst: 'Problem solving (PSST)',
  psychoeducation_anxiety: 'Understanding Anxiety (psychoeducation)',
  psychoeducation_anxiety_advanced: 'Anxiety — deeper skills (psychoeducation)',
  psychoeducation_depression: 'Understanding Low Mood (psychoeducation)',
  psychoeducation_depression_advanced: 'Low mood — deeper skills (psychoeducation)',
  psychoeducation_stress: 'Understanding Stress (psychoeducation)',
  psychoeducation_work_stress: 'Work stress (psychoeducation)',
  psychoeducation_anger: 'Anger (psychoeducation)',
  psychoeducation_sleep: 'Sleep and rest hygiene',
  psychoeducation_emotion_regulation: 'Emotion Regulation (psychoeducation)',
  psychoeducation_trauma: 'Difficult Experiences (trauma-informed)',
  psychoeducation_grief: 'Grief and Loss (psychoeducation)',
  psychoeducation_burnout: 'Exhaustion and Burnout (psychoeducation)',
  session_wai_feedback: 'Post-session alliance feedback (WAI)',
};
