/**
 * Etiquetas en inglés del catálogo de intervenciones (#127 / i18n).
 * Mantener 1:1 con claves de INTERVENTION_CATALOG.
 */
export const INTERVENTION_LABELS_EN = {
  breathing_exercise: 'Breathing Exercise',
  grounding_technique: 'Grounding Technique',
  mindfulness_reminder: 'Mindfulness Reminder',
  self_care: 'Self-Care',
  self_compassion_exercise: 'Self-Compassion Exercise',
  support_contact: 'Contact Support',
  gratitude_journal: 'Gratitude Journal',
  timeout_technique: 'Time-Out Technique',
  communication_tool: 'Communication Tool',
  boundary_setting: 'Set Boundaries',
  task_break: 'Take a Break',
  grief_support: 'Grief Support',
  memory_exercise: 'Memory Exercise',
  connection_exercise: 'Connection Exercise',
  social_activity: 'Social Activity',
  activity_suggestion: 'Activity Suggestion',
  performance_anxiety_tool: 'Performance Anxiety (brief guide)',
  present_moment_exercise: 'Back to the Present (brief exercise)',
  social_anxiety_tool: 'Social Anxiety (brief guide)',
  exposure_guide: 'Gradual Exposure (brief guide)',
  reframing_tool: 'Reframing (shift perspective)',
  task_organization: 'Organize Tasks (quick steps)',
  time_management: 'Time Management (quick tip)',
  anger_management: 'Manage Anger (brief guide)',
  physical_activity: 'Gentle Movement',
  forgiveness_work: 'Forgiveness (brief exercise)',
  values_exploration: 'Explore Values (brief guide)',
  apology_guide: 'Apologize (brief guide)',
  psychoeducation_anxiety: 'Understanding Anxiety (psychoeducation)',
  psychoeducation_depression: 'Understanding Low Mood (psychoeducation)',
  psychoeducation_stress: 'Understanding Stress (psychoeducation)',
  psychoeducation_anger: 'Anger (psychoeducation)',
  psychoeducation_sleep: 'Sleep and rest hygiene',
  psychoeducation_emotion_regulation: 'Emotion Regulation (psychoeducation)',
  psychoeducation_trauma: 'Difficult Experiences (trauma-informed)',
};
