import { StyleSheet } from 'react-native';
import { SPACING } from '../../constants/ui';
import { getFocusTheme } from '../../styles/focusCardTheme';

function tint(colors, alpha = 0.08) {
  return colors.accentLineSoft ?? `rgba(30, 131, 211, ${alpha})`;
}

export function createMicroGuideScreenStyles(colors, resolvedScheme) {
  const t = getFocusTheme(colors, resolvedScheme);
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    scrollContent: {
      paddingHorizontal: SPACING.SCREEN_EDGE_INSET,
      paddingTop: 8,
      paddingBottom: 120,
    },
    hero: {
      ...t.FOCUS_PANEL,
      alignItems: 'center',
      paddingVertical: 24,
      marginBottom: 16,
    },
    heroIcon: {
      width: 64,
      height: 64,
      borderRadius: 20,
      backgroundColor: tint(colors, 0.14),
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 14,
    },
    heroIconText: { fontSize: 32 },
    heroKicker: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      color: t.FOCUS_KICKER_COLOR,
      marginBottom: 8,
    },
    heroTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'center',
      letterSpacing: -0.3,
      lineHeight: 28,
    },
    heroLead: {
      marginTop: 12,
      fontSize: 15,
      lineHeight: 23,
      color: t.FOCUS_BODY_SOFT,
      textAlign: 'center',
      paddingHorizontal: 4,
    },
    metaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      gap: 8,
      marginTop: 16,
    },
    metaPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: tint(colors, 0.1),
    },
    metaPillText: {
      fontSize: 12,
      fontWeight: '600',
      color: t.FOCUS_META,
    },
    stepsSection: {
      marginBottom: 8,
    },
    stepsHeading: {
      fontSize: 13,
      fontWeight: '700',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
      color: t.FOCUS_KICKER_COLOR,
      marginBottom: 14,
      marginLeft: 4,
    },
    timeline: {
      gap: 0,
    },
    timelineRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
    },
    timelineRail: {
      width: 32,
      alignItems: 'center',
      marginRight: 12,
    },
    timelineDot: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1,
    },
    timelineDotText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textOnPrimary ?? colors.white ?? '#fff',
    },
    timelineLine: {
      flex: 1,
      width: 2,
      backgroundColor: tint(colors, 0.35),
      marginVertical: 2,
    },
    stepCard: {
      flex: 1,
      ...t.FOCUS_INNER_ROW,
      flexDirection: 'column',
      alignItems: 'stretch',
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 12,
    },
    stepTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 8,
      lineHeight: 22,
    },
    stepBody: {
      fontSize: 15,
      lineHeight: 24,
      color: t.FOCUS_BODY_SOFT,
    },
    tipCard: {
      borderRadius: 16,
      padding: 14,
      marginTop: 4,
      marginBottom: 16,
      borderLeftWidth: 3,
      borderLeftColor: colors.primary,
      backgroundColor: tint(colors, 0.08),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: t.FOCUS_BORDER_SUBTLE,
    },
    tipLabel: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      color: t.FOCUS_KICKER_COLOR,
      marginBottom: 6,
    },
    tipBody: {
      fontSize: 14,
      lineHeight: 21,
      color: colors.textSecondary,
    },
    disclaimer: {
      fontSize: 12,
      lineHeight: 18,
      color: t.FOCUS_META,
      textAlign: 'center',
      marginTop: 8,
      fontStyle: 'italic',
    },
    footer: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: SPACING.SCREEN_EDGE_INSET,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: t.FOCUS_BORDER_SUBTLE,
      backgroundColor: colors.background,
    },
    primaryBtn: {
      paddingVertical: 15,
      borderRadius: 16,
      backgroundColor: colors.primary,
      alignItems: 'center',
    },
    primaryBtnText: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textOnPrimary ?? colors.white ?? '#fff',
    },
    doneHero: {
      ...t.FOCUS_PANEL,
      alignItems: 'center',
      paddingVertical: 32,
      marginTop: 8,
    },
    doneIconWrap: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: colors.successSoft ?? tint(colors, 0.12),
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    doneTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 10,
    },
    doneBody: {
      fontSize: 15,
      lineHeight: 23,
      color: t.FOCUS_BODY_SOFT,
      textAlign: 'center',
      paddingHorizontal: 8,
    },
    doneBtn: {
      marginTop: 24,
      paddingVertical: 14,
      paddingHorizontal: 28,
      borderRadius: 999,
      backgroundColor: colors.accentLineSoft,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: t.FOCUS_ACCENT_BORDER,
    },
    doneBtnText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.primary,
    },
    centerBox: {
      paddingVertical: 48,
      alignItems: 'center',
      gap: 12,
    },
    errorText: {
      fontSize: 15,
      color: colors.error,
      textAlign: 'center',
      lineHeight: 22,
    },
  });
}
