/**
 * Estilos compartidos para pantallas en screens/techniques (alineados al tema foco).
 */
import { StyleSheet } from 'react-native';
import { colors } from '../../styles/globalStyles';
import {
  FOCUS_ACCENT_BORDER,
  FOCUS_BORDER_SUBTLE,
  FOCUS_KICKER_COLOR,
  FOCUS_META,
  FOCUS_PANEL,
} from '../../styles/focusCardTheme';

export const techniqueScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 120,
  },
  introPanel: {
    ...FOCUS_PANEL,
    marginBottom: 16,
  },
  introKicker: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: FOCUS_KICKER_COLOR,
    marginBottom: 10,
  },
  introTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.white,
    marginBottom: 8,
    lineHeight: 26,
  },
  introText: {
    fontSize: 15,
    color: FOCUS_META,
    lineHeight: 22,
  },
  card: {
    backgroundColor: colors.cardBackground,
    borderRadius: 22,
    padding: 16,
    marginBottom: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: FOCUS_BORDER_SUBTLE,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.white,
    marginBottom: 4,
  },
  cardMeta: {
    fontSize: 13,
    color: FOCUS_META,
    marginBottom: 10,
  },
  cardBody: {
    fontSize: 15,
    color: FOCUS_META,
    lineHeight: 22,
    marginBottom: 14,
  },
  primaryButton: {
    alignSelf: 'flex-start',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 14,
    backgroundColor: 'rgba(26, 221, 219, 0.18)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: FOCUS_ACCENT_BORDER,
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
  },
  stopButton: {
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 107, 107, 0.16)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 107, 107, 0.35)',
    alignItems: 'center',
  },
  stopButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.92)',
  },
  iconTile: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: 'rgba(26, 221, 219, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  rowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoColumn: {
    flex: 1,
    minWidth: 0,
  },
  cardCategory: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: FOCUS_KICKER_COLOR,
  },
  cardSelected: {
    borderWidth: 2,
    borderColor: colors.primary,
  },
  activePanel: {
    backgroundColor: colors.cardBackground,
    borderRadius: 22,
    padding: 24,
    alignItems: 'center',
    alignSelf: 'stretch',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: FOCUS_ACCENT_BORDER,
  },
  timerText: {
    fontSize: 44,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 8,
  },
  timerLabel: {
    fontSize: 14,
    color: FOCUS_META,
  },
  selectedRow: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: FOCUS_BORDER_SUBTLE,
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedRowText: {
    fontSize: 14,
    color: colors.success,
    marginLeft: 8,
    fontWeight: '600',
  },
  formBlock: {
    marginTop: 8,
  },
  formSectionHeading: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.white,
    marginBottom: 8,
    lineHeight: 24,
  },
  formHint: {
    fontSize: 14,
    color: FOCUS_META,
    lineHeight: 20,
    marginBottom: 12,
  },
  textInput: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: FOCUS_BORDER_SUBTLE,
    padding: 14,
    color: colors.white,
    fontSize: 15,
    lineHeight: 22,
    minHeight: 120,
    marginBottom: 14,
  },
  textInputTall: {
    minHeight: 160,
  },
  saveButton: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: 'rgba(26, 221, 219, 0.2)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: FOCUS_ACCENT_BORDER,
    alignItems: 'center',
  },
  saveButtonDisabled: {
    opacity: 0.45,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.white,
  },
  secondaryButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: FOCUS_BORDER_SUBTLE,
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: FOCUS_KICKER_COLOR,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'stretch',
  },
  promptText: {
    fontSize: 14,
    fontWeight: '600',
    color: FOCUS_KICKER_COLOR,
    marginBottom: 10,
    lineHeight: 20,
  },
  cardCompleted: {
    borderColor: 'rgba(76, 175, 80, 0.55)',
    opacity: 0.95,
  },
  actionButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: 'rgba(26, 221, 219, 0.18)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: FOCUS_ACCENT_BORDER,
    alignItems: 'center',
  },
  actionButtonCompleted: {
    backgroundColor: 'rgba(76, 175, 80, 0.15)',
    borderColor: 'rgba(76, 175, 80, 0.4)',
  },
  actionButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
  },
  actionButtonTextCompleted: {
    color: colors.success,
  },
  navRow: {
    flexDirection: 'row',
    gap: 12,
    alignSelf: 'stretch',
    marginBottom: 16,
  },
  navButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: FOCUS_BORDER_SUBTLE,
    alignItems: 'center',
  },
  navButtonDisabled: {
    opacity: 0.45,
  },
  navButtonPrimary: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  navButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.white,
  },
  navButtonTextMuted: {
    fontSize: 15,
    fontWeight: '600',
    color: FOCUS_KICKER_COLOR,
  },
  ctaHero: {
    marginTop: 8,
    paddingVertical: 28,
    paddingHorizontal: 24,
    borderRadius: 22,
    backgroundColor: 'rgba(26, 221, 219, 0.2)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: FOCUS_ACCENT_BORDER,
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  ctaHeroTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.white,
    marginTop: 12,
    textAlign: 'center',
  },
  ctaHeroSub: {
    fontSize: 14,
    color: FOCUS_META,
    marginTop: 8,
    textAlign: 'center',
  },
  stepMeta: {
    fontSize: 13,
    color: FOCUS_META,
    fontWeight: '600',
    marginBottom: 8,
  },
  stepTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.white,
    marginBottom: 12,
  },
  stepDescription: {
    fontSize: 15,
    color: FOCUS_META,
    lineHeight: 22,
  },
  stepIconLarge: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: 'rgba(26, 221, 219, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  inlineBackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 8,
  },
  inlineBackLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
  },
  practiceBlock: {
    ...FOCUS_PANEL,
    padding: 20,
  },
  practiceExample: {
    fontSize: 14,
    color: FOCUS_META,
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 20,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: FOCUS_BORDER_SUBTLE,
  },
  listGap: {
    gap: 14,
  },
});
